v<-c(13,22,28,7,31)
plot(v,type = "s")
plot(v,type="o")
plot(v,type="s",col="green",xlab="Month",ylab = "temp")
v<-c(13,22,28,7,31)
w<-c(11,13,32,6,35)
x<-c(12,22,15,34,35)
plot(v,type="o",col="green",xlab="month",ylab="temp")
lines(w,type="c",col="red")
lines(x,type="c",col="blue")
x<-c(5,7,8,7,2,2,9,4,11,12,9,6)
y<-c(99,86,87,88,111,103,87,94,78,77,85,86)
plot(x,y)
plot(x,y,main="Result",xlab="x",ylab="y")
plot(x,y,col="blue",cex=2)
data<-mtcars[,c('cyl','mpg')]
dim(mtcars)
png(file="scatterplot final2.png")
plot(x=data$cyl,y=data$mpg,xlab="weight",ylab="Mil",xlim=c(2.5,5),ylim=c(15,30),main = "weight v/s Mil")
dev.off()
temp<-c(22,25,26,27,52,20)
result<-barplot(temp)
print(result)
result<-barplot(temp,main = "result",xlab="x",ylab="y")
result<-barplot(temp,main = "result",xlab="x",ylab="y",names.arg = c("sun","mon","tue","wed","thr","sat"),col="blue")
result<-barplot(temp,main = "result",xlab="x",ylab="y",names.arg = c("sun","mon","tue","wed","thr","sat"),col="blue",density=8)
result<-barplot(temp,main = "result",xlab="x",ylab="y",names.arg = c("sun","mon","tue","wed","thr","sat"),col="blue",density=8,horiz=TRUE,border = "red")
data<-matrix(c(122,203,167,118,528,178,673,212),nrow=2,ncol=4)
data
result<-barplot(data,main="title",xlab="class",names.arg = c("1st","2nd","3rd","4th"),col=c("red","green"))
legend("topright",c("row1","row2"),fill=c("red","green"))
legend("topleft",c("row1","row2"),fill=c("red","green"))
data<-matrix(c(2.8,2.3,2.3,1.0,3.8,1.8,2.73,3.2),nrow=1,ncol=8)
data
colors<-c("yellow","brown","green","blue","purple","orange","pink","black")
result<-barplot(data,main="tgpa",xlab="sem",names.arg = c("1st","2nd","3rd","4th","5th","6th","7th","8th"),col=colors)
A<-c(17,32,8,53,1)
barplot(A,xlab="x",ylab="y",horiz=TRUE)
B<-c("jan","feb","mar","apr","may")
barplot(A,names.arg = B)
data<-matrix(c(2.8,2.3,2.3,1.0,3.8,1.8,2.73,3.2),nrow=2,ncol=4)
data
colors<-c("yellow","brown","green","blue","purple","orange","pink","black")
result<-barplot(data,main="tgpa",xlab="sem",names.arg = c("1st","2nd","3rd","4th","5th","6th","7th","8th"),col=colors,beside = TRUE)
legend("topleft",regions=0.7,cex=0.,fill=colors)
data<-matrix(c(7,8,9,10,11,12,6,3,4,2,1,8,2,5,6,7,5,1),nrow = 3,byrow=TRUE)
data
colors<-c("green","blue","red")
result<-barplot(data,main="cgpa",xlab="sem",names.arg=c("sem1","sem2","sem3","sem4","sem5","sem6"),col=colors,beside=TRUE)
x<-c(23,56,20,63)
labels<-c("a","b","c","d")
pie(x,labels)
pie(x,labels,main="pie chart")
