install.packages("plotrix")
library(plotrix)
x<-c(600,300,150,100,200)
pie3D(x,main="3Dpie",labels=c("a","b","c","d","e"),col=c("green","blue","red","yellow","orange"))
x<-c(1,2,3,4,5)
y<-c(100,200,600,400,500)
plot(x,y,type="l",col="lightblue",lwd=10)
plot(x,y,type="s",main='type="s"')
plot(x,y,type="s",lwd=2,lty=1,main="lty=1")
plot(x,y,type="s",lwd=2,lty=3,main="lty=1")
plot(x,y,type="s",lwd=2,lty=3,main="lty=1")
plot(x,y,type="s",lwd=2,lty=4,main="lty=1")
plot(x,y,type="s",lwd=2,lty=5,main="lty=1")
plot(x,y,type="s",lwd=2,lty=6,main="lty=1")
plot(x,y,type="s",main='type="l"')
plot(x,y,type="s",lwd=2,lty=1,main="lty=1")
plot(x,y,type="s",lwd=2,lty=3,main="lty=1")
plot(x,y,type="s",lwd=2,lty=3,main="lty=1")
plot(x,y,type="s",lwd=2,lty=4,main="lty=1")
plot(x,y,type="s",lwd=2,lty=5,main="lty=1")
plot(x,y,type="s",lwd=2,lty=6,main="lty=1")
plot(x,y,type="b",cex=1,pch=5,col="red")
plot(x,y,type="b",cex=0,pch=5,col="red")
plot(x,y,type="b",cex=3,pch=LETTERS[1:5],col=1:5,xlim=c(0,6),ylim=c(50,800))
install.packages("ggplot2")
library(ggplot2)
View(iris)
ggplot(data=iris)
p<-ggplot(data = iris,aes(x=Sepal.Length,y=Sepal.Width))
p+geom_point()
ggplot(data = iris,aes(x=Sepal.Length,y=Sepal.Width))+geom_point()
ggplot(data = iris,aes(x=Sepal.Length,y=Sepal.Width))+geom_point()+facet_wrap(~Species)
ggplot(data = iris,aes(x=Sepal.Length,y=Sepal.Width))+geom_point()+facet_wrap(~Species)+geom_smooth(method = "lm")
library(dplyr)
ggplot(filter(iris,Species=="setosa"),aes(x=Sepal.Length,y=Sepal.Width))+geom_point()+coord_cartesian(xlim=c(4,8),ylim=c(2,5))       
ggplot(filter(iris,Species=="setosa"),aes(x=Sepal.Length,y=Sepal.Width))+geom_point()+facet_wrap(~Species)+geom_smooth(method="lm")+theme(axistext=element_text(color="green",size=6))       
ggplot(data = iris,aes(y=Petal.Length,x=Sepal.Length))+geom_point()
